### PR TITLE
release 4.0.0

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by alexjfisher** [comment]
Is there anything else you want to do before our first release?

eg.

* README still refers to Centos 5
* Mention the migration to VP in the README
* Data types?  (especially if adding them is likely to be a breaking change).

**Comment by dhollinger** [comment]
@alexjfisher @bastelfreak - is there anything still needed for this to get merged?

**Comment by alexjfisher** [comment]
There are still a couple of deprecated parameters that are documented as going to be removed in 4.0.0

**Comment by alexjfisher** [comment]
Here's some more info. https://github.com/voxpupuli/puppet-snmp/issues/53

**Comment by alexjfisher** [comment]
If I'm reading all of that correctly, the plan was to remove 'traditional access control' completely in version 4.0?  But that was then (2015).  Do we still want to do this?

@razorsedge - Do you still think this is something that should be done?  If we are to do this, before the first VP release is the ideal opportunity.

**Comment by alexjfisher** [comment]
More info in https://github.com/voxpupuli/puppet-snmp/commit/84bab501f58c9b3fcd474fdd224d3c485e930e12

**Comment by alexjfisher** [comment]
Ping @ekohl any thoughts?

**Comment by alexjfisher** [comment]
@trevor-vaughan Old versions of net-snmp that don't support VACM on OSes that we support?

**Comment by Dan33l** [comment]
duplicate with #162

**Pull request closed without merging**
