### PR TITLE
Run snmptrapd in debian too

### PR DESCRIPTION
**Pull request by amateo**
In latest ubuntu, snmptrapd is provided by a different package than snmpd.
This patch is to install this new package and configure snmptrapd in this system.

### CODE REVIEW

**Comment by razorsedge** [comment]
@amateo Thank you for your submission. As per the CONTRIBUTING.md file, could you please resubmit from the develop branch?

**Comment by amateo** [comment]
I have created a new PR #119

**Comment by amateo** [comment]
I have created a new PR #119

**Comment by amateo** [comment]
I made the new #168. This PR can be closed.

**Pull request closed without merging**
