### PR TITLE
Run snmptrapd in ubuntu xenial too

### PR DESCRIPTION
**Pull request by amateo**
In latest ubuntu, snmptrapd is provided by a different package than snmpd.
This patch is to install this new package and configure snmptrapd in this system.

I have previously submited this same PR in #114 and #119 but it seems there was problem.

Could you check if this PR is ok?

### CODE REVIEW

**Comment by amateo** [comment]
Hi @razorsedge, I've been reviewing this PR. I think that CI fails are not directly related with the change I made. Could you review it? Is there any way to rerun CI?

**Comment by amateo** [comment]
Hi @bastelfreak. Is there any reason to close this PR?

**Comment by bastelfreak** [comment]
I was confused for a bit here. The develop branch is gone since all changes got merged into master. The PR got closed automatically by deleting the develop branch. Can you please resubmit against the master branch? I'm happy to review this.

**Comment by amateo** [comment]
There was already another PR #114. In that @razorsedge asked me to do it from develop.
Since #114 is still open, is that good for you?

**Pull request closed without merging**
