### PR TITLE
fix user and group name change from snmp to Debian-snmp in Ubuntu 18.04

### PR DESCRIPTION
**Pull request by david-barbion**

### CODE REVIEW

**Comment by cmezzett** [comment]
@razorsedge please merge this PR, it would be wonderful to have this module working on Ubuntu 18.04 without the need to fork
TIA

**Comment by bastelfreak** [comment]
Hi @david-barbion, this module got recently migrated to Vox Pupuli. This is similar to https://github.com/voxpupuli/puppet-snmp/pull/130. I'm fine with merging with whatever is ready first. Please add all supported operating systems to the ```metadata.json``` file, also a unit test with rspec-puppet-facts would be nice and a rebase is required.

**Comment by cliff-wakefield** [comment]
I don't believe this or PR #130 are needed anymore after PR #134

**Comment by alexjfisher** [comment]
I think this *is* still needed.
See https://github.com/voxpupuli/puppet-snmp/issues/151

**Comment by Dan33l** [comment]
Looks to be done : by #130 
https://github.com/voxpupuli/puppet-snmp/commit/7ab970b3e36d8531d2effb12c17aa1ca9ece86b8

**Pull request closed without merging**
